[package]
name = "emstar"
version = "0.2.0"
edition = "2024"
description = "Read, write, and inspect STAR files used in cryo-EM/ET (RELION)"
license = "MIT"
repository = "https://github.com/elemeng/emstar"
keywords = ["star", "cryo-em", "relion", "starfile"]
categories = ["science", "parser"]

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
polars = { version = "0.45", default-features = false, features = ["performant"], optional = true }

[features]
default = []
cli = ["dep:clap"]
polars = ["dep:polars"]

[profile.release]
opt-level = 3
strip = true
